import Head from 'next/head';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import CardFeatured from '@/components/Featured/cardFeatured';
import { useState, useEffect } from 'react';
import { Grid, Pagination} from '@mui/material'
import usePagination from './usePagination'
import { BsSearch } from "react-icons/bs";

export default function index({product}){
    const [data,setData] = useState(product)
    const [searchData,setSearchData] = useState('')
    console.log(data)
    const [page, setPage] = useState(1)

  // pagination
    const PER_PAGE = 10
    const count = Math.ceil(data.length/PER_PAGE)
    const _DATA = usePagination(data, PER_PAGE)
    const handleChange =(e, p)=>{
        setPage(p)
        _DATA.jump(p)
    }

    const handleSearchData = (e) =>{
        setSearchData(e.target.value);
    }

    const searchProduct = (temp) =>{
        if(!searchData) {
            return temp
        }
        const searchProduct = searchData.toLowercase()
        const foundProduct = temp.filter((data)=>data.name.toLowerCase().includes(searchProduct) || data.brand.toLowerCase().includes(searchProduct))
        return foundProduct
    }

    useEffect(()=>{
        let filterData = searchProduct(filterData)
        setData(filterData)
    }, [searchData])

    return (
        <>
            <Head>
                <title>CashLess Shop | All Game</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon/logoo.png" />
            </Head>
            <Navbar/>
            
            <div className="product container my-5">
                <div className="search d-flex rounded my-5" action="action_page.php">
                   <input type="search" 
                    className="form-control rounded border"  
                    placeholder="Search.." 
                    name="search"
                    onChangeInput={handleSearchData}
                    />
                    <button 
                        className="border border-light bg-transparent border-0"
                        >
                        <BsSearch className="m-2"/>
                    </button>
                </div>
                <div className="product-item flex d-flex flex-wrap gap-5 justify-content-center">
                    {data?.length !=0 && _DATA.currentData().map((data) => (
                        <div key={data.id}>
                            <CardFeatured id={data.id} img={data.img} title={data.name} type={data.type}/>
                        </div>
                    )) }
                    <Grid 
                        container
                        direction="column"
                        alignItems="center"
                        justifyContent="center"
                        spacing={2}>
                        <Grid item xs={3}>
                            <Pagination
                            count={count}
                            page={page}
                            variant='outlined'
                            shape='rounded'
                            onChange={handleChange}
                            color='primary'
                            boundaryCount={2}
                            />
                        </Grid>
                    </Grid>
                </div>
               
            </div>
            <Footer/>
        </>
    )
}
export async function getStaticProps(){
    try{
        const res = await fetch('http://localhost:3000/api/product')
        const product = await res.json()
        return {
            props:{
                product
            }
        }
    }
    catch(err){
        console.error(err)
    }
    return {
        props: {
            product
        }
    }
}
