import React, { useEffect} from 'react'
import AOS from 'aos'
import Head from 'next/head'
import Navbar from "components/Navbar/index"
import Footer from "components/Footer/index"
import Banner from '@/components/Banner';
import Guide from '@/components/Guide'
import Featured from '@/components/Featured'


export default function Home({product}) {
  useEffect(() => {
    AOS.init();
  }, []);

  console.log(product)

  
  return (
    <>
        <Head>
            <title>CashLess Shop</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon/logoo.png" />
        </Head>
        <Navbar/>
        <Banner/>
        <Guide/>
        <Featured dataProduct={product}/>
        <Footer/>

    </>
  )
}
export async function getStaticProps(){
  try{
    const res = await fetch('http://localhost:3000/api/product')
    const product = await res.json()
    return {
      props:{
        product
      }
    }
  }
  catch(err){
    console.error(err)
  }
  return {
    props:{
      product
    }
  }
}
