import React, { } from 'react'
import AOS from 'aos'
import Head from 'next/head'
import Banner from '@/components/Banner';
import Guide from '@/components/Guide'
import Featured from '@/components/Featured'
import { useState, useEffect } from 'react'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';


export default function Home({product}) {
  const [popular, setPopular] = useState()
  useEffect(() => {
    AOS.init();
  });

  
  
  useEffect(() => {
    const temp = product.filter((popular) => popular.rate >= 4)
    setPopular(temp)
  },[])

  
  return (
    <>
        <Head>
            <title>CashLess Shop</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon/logoo.png" />
        </Head>
        <Navbar/>
        <Banner/>
        <Guide/>
        <Featured dataProduct={popular}/>
        <Footer/>
    </>
  )
}
export async function getStaticProps(){
  try{
    const res = await fetch('http://localhost:3000/api/product')
    const product = await res.json()
    return {
      props:{
        product
      }
    }
  }
  catch(err){
    console.error(err)
  }
  return {
    props:{
      product
    }
  }
}
